wip: try union Position
    info NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
  CommerceSim.Core net11.0 failed with 2 error(s) and 1 warning(s) (0.1s)
    /Users/jfoshee/source/CommerceSim/CommerceSim.Core/Spatial/SpatialSystem.cs(61,55): warning CS8509: The switch expression does not handle all possible values of its input type (it is not exhaustive). For example, the pattern '_' is not covered.
    /Users/jfoshee/source/CommerceSim/CommerceSim.Core/Spatial/SpatialSystem.cs(83,25): error CS0019: Operator '-' cannot be applied to operands of type 'Position' and 'Position'
    /Users/jfoshee/source/CommerceSim/CommerceSim.Core/Sim.cs(36,37): error CS1503: Argument 1: cannot convert from '(CommerceSim.Core.IEntity entity, int? initialPosition)[]' to '(CommerceSim.Core.IEntity entity, CommerceSim.Core.Spatial.Position? position)'

Build failed with 2 error(s) and 1 warning(s) in 0.6s